[build]
  publish = "capacity_checker/staticfiles"
  command = "echo 'No build step required for Django static files'"

[context.production.environment]
  DJANGO_SETTINGS_MODULE = "capacity_checker.settings"
