# Generated by Django 5.1.6 on 2025-06-21 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TradingAdvert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_offer",
                    models.BooleanField(
                        default=True, help_text="True=Selling, False=Buying"
                    ),
                ),
                ("capacity_mw", models.DecimalField(decimal_places=2, max_digits=7)),
                ("delivery_year", models.IntegerField()),
                (
                    "price_gbp_per_kw_yr",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Leave blank for POA",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("description", models.TextField(max_length=1000)),
                ("contact_email", models.EmailField(max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("is_paid", models.BooleanField(default=False)),
                (
                    "stripe_payment_intent_id",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Trading Advert",
                "verbose_name_plural": "Trading Adverts",
                "ordering": ["-created_at"],
            },
        ),
    ]
