# Generated by Django 5.1.6 on 2025-06-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trades", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradingadvert",
            name="capacity_flexible",
            field=models.BooleanField(
                default=False, help_text="Capacity amount is negotiable/flexible"
            ),
        ),
        migrations.AddField(
            model_name="tradingadvert",
            name="price_estimate",
            field=models.BooleanField(
                default=False, help_text="Price is indicative/estimate only"
            ),
        ),
    ]
