# Generated by Django 5.1.6 on 2025-06-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trades", "0003_tradingadvert_show_email_publicly_tradingmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tradingmessage",
            name="sender_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
