# Generated by Django 5.1.6 on 2025-06-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trades", "0004_alter_tradingmessage_sender_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradingadvert",
            name="edit_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tradingadvert",
            name="extension_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tradingadvert",
            name="last_edited",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tradingadvert",
            name="original_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
