# Generated by Django 5.1.6 on 2025-05-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_registrationemailrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="free_access_start_time",
            field=models.DateTimeField(
                blank=True,
                help_text="When the user's free access period started.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="reminder_email_sent",
            field=models.BooleanField(
                default=False,
                help_text="Whether a reminder email has been sent for expired free access.",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="reminder_email_sent_at",
            field=models.DateTimeField(
                blank=True, help_text="When the reminder email was sent.", null=True
            ),
        ),
    ]
