# Generated by Django on 2025-01-27
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_free_access_start_time_and_more'),
    ]

    operations = [
        # Enable RLS on user profile (user-specific access)
        migrations.RunSQL(
            sql="ALTER TABLE accounts_userprofile ENABLE ROW LEVEL SECURITY;",
            reverse_sql="ALTER TABLE accounts_userprofile DISABLE ROW LEVEL SECURITY;",
        ),
        # Enable RLS on registration email records (system only)
        migrations.RunSQL(
            sql="ALTER TABLE accounts_registrationemailrecord ENABLE ROW LEVEL SECURITY;",
            reverse_sql="ALTER TABLE accounts_registrationemailrecord DISABLE ROW LEVEL SECURITY;",
        ),
    ]