# Generated by Django 5.1.6 on 2025-06-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_enable_userprofile_rls"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="payment_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Amount paid for access (£2 = lists only, £5 = full access)",
                max_digits=6,
                null=True,
            ),
        ),
    ]
