# Generated by Django 5.1.6 on 2025-06-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_userprofile_payment_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="trial_first_use",
            field=models.DateTimeField(
                blank=True,
                help_text="When user first accessed the site in current trial week.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="trial_hours_used",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Hours used in current trial cycle.",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="trial_week_start",
            field=models.DateTimeField(
                blank=True,
                help_text="When the current 7-day trial cycle started.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="free_access_start_time",
            field=models.DateTimeField(
                blank=True,
                help_text="LEGACY: When the user's free access period started.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="reminder_email_sent",
            field=models.BooleanField(
                default=False,
                help_text="LEGACY: Whether a reminder email has been sent for expired free access.",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="reminder_email_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="LEGACY: When the reminder email was sent.",
                null=True,
            ),
        ),
    ]
