# Generated by Django 5.1.6 on 2025-05-21 22:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("checker", "0012_add_full_text_search"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="component",
            name="county_outward_idx",
        ),
        migrations.RemoveIndex(
            model_name="component",
            name="component_search_idx",
        ),
        migrations.RemoveField(
            model_name="component",
            name="search_vector",
        ),
    ]
