# Generated by Django 5.1.6 on 2025-05-25 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checker", "0013_remove_component_county_outward_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyLinks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("auction_links", models.JSONField(default=list)),
                ("component_count", models.IntegerField(default=0)),
                ("auction_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Company Links",
                "ordering": ["company_name"],
            },
        ),
        migrations.CreateModel(
            name="LocationGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("component_count", models.IntegerField(db_index=True, default=0)),
                ("displayed_capacity_mw", models.FloatField(default=0.0)),
                (
                    "normalized_capacity_mw",
                    models.FloatField(db_index=True, default=0.0),
                ),
                (
                    "capacity_confidence",
                    models.CharField(default="none", max_length=20),
                ),
                ("is_aggregated_cmu", models.BooleanField(default=False)),
                ("cmu_location_count", models.IntegerField(default=1)),
                ("capacity_source", models.CharField(max_length=50, null=True)),
                ("capacity_calculation_notes", models.TextField(null=True)),
                ("auction_years", models.JSONField(default=list)),
                ("technologies", models.JSONField(default=dict)),
                ("companies", models.JSONField(default=dict)),
                ("descriptions", models.JSONField(default=list)),
                ("latitude", models.FloatField(blank=True, db_index=True, null=True)),
                ("longitude", models.FloatField(blank=True, db_index=True, null=True)),
                (
                    "county",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "outward_code",
                    models.CharField(
                        blank=True, db_index=True, max_length=5, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "representative_component",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="location_groups",
                        to="checker.component",
                    ),
                ),
            ],
            options={
                "ordering": ["-component_count", "location"],
                "indexes": [
                    models.Index(
                        fields=["-component_count"], name="loc_group_count_idx"
                    ),
                    models.Index(
                        fields=["county", "outward_code"], name="loc_group_geo_idx"
                    ),
                    models.Index(
                        fields=["latitude", "longitude"], name="loc_group_spatial_idx"
                    ),
                ],
            },
        ),
    ]
