# Generated by Django 5.1.6 on 2025-05-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checker", "0014_add_locationgroup_and_companylinks"),
    ]

    operations = [
        migrations.AddField(
            model_name="locationgroup",
            name="cmu_ids",
            field=models.JSONField(default=list),
        ),
    ]
