# Generated by Django 5.1.6 on 2025-05-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checker", "0015_add_cmu_ids_to_locationgroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="locationgroup",
            name="is_active",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
