# Generated by Django on 2025-01-27
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0017_add_gin_indexes_to_locationgroup'),
    ]

    operations = [
        migrations.RunSQL(
            # Drop the unused trigger first
            sql="DROP TRIGGER IF EXISTS search_vector_update ON checker_component;",
            reverse_sql="",
        ),
        migrations.RunSQL(
            # Drop the unused function
            sql="DROP FUNCTION IF EXISTS public.components_search_vector_update() CASCADE;",
            reverse_sql="",
        ),
        migrations.RunSQL(
            # Create a dedicated schema for extensions if it doesn't exist
            sql="CREATE SCHEMA IF NOT EXISTS extensions;",
            reverse_sql="DROP SCHEMA IF EXISTS extensions CASCADE;",
        ),
        migrations.RunSQL(
            # Move pg_trgm extension to the extensions schema
            sql="""
                -- Drop from public schema first if it exists
                DROP EXTENSION IF EXISTS pg_trgm CASCADE;
                -- Create in extensions schema
                CREATE EXTENSION IF NOT EXISTS pg_trgm SCHEMA extensions;
            """,
            reverse_sql="""
                DROP EXTENSION IF EXISTS pg_trgm CASCADE;
                CREATE EXTENSION IF NOT EXISTS pg_trgm SCHEMA public;
            """,
        ),
    ]