# Generated by Django on 2025-01-27
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0018_cleanup_unused_search_features'),
    ]

    operations = [
        # Enable RLS on checker app tables (public read access)
        migrations.RunSQL(
            sql="ALTER TABLE checker_companylinks ENABLE ROW LEVEL SECURITY;",
            reverse_sql="ALTER TABLE checker_companylinks DISABLE ROW LEVEL SECURITY;",
        ),
        migrations.RunSQL(
            sql="""
                CREATE POLICY "Public read access for company links" ON checker_companylinks
                    FOR SELECT USING (true);
            """,
            reverse_sql="DROP POLICY IF EXISTS \"Public read access for company links\" ON checker_companylinks;",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE checker_locationgroup ENABLE ROW LEVEL SECURITY;",
            reverse_sql="ALTER TABLE checker_locationgroup DISABLE ROW LEVEL SECURITY;",
        ),
        migrations.RunSQL(
            sql="""
                CREATE POLICY "Public read access for location groups" ON checker_locationgroup
                    FOR SELECT USING (true);
            """,
            reverse_sql="DROP POLICY IF EXISTS \"Public read access for location groups\" ON checker_locationgroup;",
        ),
    ]