# Generated by Django 5.1.6 on 2025-06-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checker", "0020_enable_rls_on_all_tables"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="full_postcode",
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
    ]
