# Generated by Django 5.1.6 on 2025-06-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checker", "0021_component_full_postcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="places_api_business_name",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="component",
            name="places_api_confidence",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="component",
            name="places_api_last_checked",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
