# Generated by Django 5.1.6 on 2025-06-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checker", "0022_add_places_api_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="places_api_business_type",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="component",
            name="places_api_major_retailers",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="component",
            name="places_api_search_strategy",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
