# Generated by Django 5.1.6 on 2025-07-06 10:45

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checker", "0024_add_trgm_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255, unique=True)),
                ("normalized_name", models.CharField(db_index=True, max_length=255)),
                ("component_count", models.IntegerField(default=0)),
                (
                    "total_capacity_mw",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("search_result_html", models.TextField(blank=True)),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_component_update", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "checker_company",
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["search_vector"], name="checker_com_search__5c2846_gin"
                    ),
                    models.Index(
                        fields=["normalized_name"],
                        name="checker_com_normali_e9a11d_idx",
                    ),
                    models.Index(
                        fields=["component_count"],
                        name="checker_com_compone_5a3dd2_idx",
                    ),
                    models.Index(
                        fields=["total_capacity_mw"],
                        name="checker_com_total_c_ad687b_idx",
                    ),
                    models.Index(
                        fields=["last_component_update"],
                        name="checker_com_last_co_0eba72_idx",
                    ),
                ],
            },
        ),
    ]
