# Generated by Django 5.1.6 on 2025-07-06 10:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("checker", "0025_add_company_model"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="company",
            name="checker_com_search__5c2846_gin",
        ),
        migrations.RemoveField(
            model_name="company",
            name="search_vector",
        ),
    ]
