# Generated by Django 5.1.6 on 2025-07-06 13:29

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("checker", "0026_simplify_company_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="locationgroup",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                blank=True, null=True
            ),
        ),
    ]
