# Generated by Django 5.1.6 on 2025-07-06 13:29

from django.db import migrations
from django.contrib.postgres.search import SearchVector


def populate_search_vectors(apps, schema_editor):
    """
    Populate search vectors for all LocationGroup instances with weighted content
    """
    LocationGroup = apps.get_model('checker', 'LocationGroup')
    
    # Update search vectors with weighted content
    # A = highest weight (location, county)
    # B = medium weight (company/technology names)  
    # C = lower weight (descriptions, CMU IDs)
    LocationGroup.objects.update(
        search_vector=(
            SearchVector('location', weight='A', config='english') +
            SearchVector('county', weight='A', config='english') +
            SearchVector('companies', weight='B', config='english') +
            SearchVector('technologies', weight='B', config='english') +
            SearchVector('descriptions', weight='C', config='english') +
            SearchVector('cmu_ids', weight='C', config='english')
        )
    )


def reverse_populate_search_vectors(apps, schema_editor):
    """
    Clear search vectors (reverse operation)
    """
    LocationGroup = apps.get_model('checker', 'LocationGroup')
    LocationGroup.objects.update(search_vector=None)


class Migration(migrations.Migration):
    dependencies = [
        ("checker", "0027_add_search_vector_field"),
    ]

    operations = [
        migrations.RunPython(
            populate_search_vectors,
            reverse_populate_search_vectors,
        ),
    ]
