# Generated by Django 5.1.6 on 2025-07-06 13:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("checker", "0028_populate_search_vectors"),
    ]

    operations = [
        migrations.RunSQL(
            # Create GIN index for fast full-text search on search vector
            sql=[
                "CREATE INDEX IF NOT EXISTS locationgroup_search_vector_gin_idx ON checker_locationgroup USING GIN (search_vector);",
            ],
            reverse_sql=[
                "DROP INDEX IF EXISTS locationgroup_search_vector_gin_idx;",
            ]
        ),
    ]
